---
- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
- name: Install required packages
  yum:
    name:
      - jq
      - vim
      - bc
      - unzip
      - wget
      - curl
      - mailx
      #- python3-libsemanage
    state: latest
- name: Install required packages via pip
  pip:
    name:
      - jmespath
      #- selinux
    state: latest
  tags:
    - pip-task
