# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cookstyle'
gem 'highline'
gem 'inspec'
gem 'inspec-bin'
gem 'inspec-core'
gem 'kitchen-ansible'
gem 'kitchen-docker'
gem 'kitchen-ec2'
gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'pry-byebug'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'test-kitchen'
