source "https://rubygems.org"

gem "test-kitchen"
gem "highline"
gem "inspec"
gem "inspec-bin"
gem "inspec-core"
gem "kitchen-ansible"
gem "kitchen-docker"
gem "kitchen-ec2"
gem "kitchen-inspec"
gem "kitchen-sync"
gem "kitchen-vagrant"
gem "rake"
gem "rubocop"
gem "cookstyle"
