---
driver:
  name: ec2
  associate_public_ip: true
  instance_type: c5.large
  ebs_optimized: true
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        delete_on_termination: true
        volume_size: 30
        volume_type: gp2
  interface: public
  require_chef_for_busser: false
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: all
  # require_ansible_repo: false
  # require_ansible_omnibus: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_binary_path: /usr/local/bin
  require_pip3: true
  ansible_verbose: true
  roles_path: spec/ansible/roles
  galaxy_ignore_certs: true
  requirements_path: spec/ansible/roles/requirements.yml
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

lifecycle:
  pre_converge:
    - remote: |
        echo "NOTICE - Installing needed packages"
        sudo yum install -y --nogpgcheck bc bind-utils redhat-lsb-core vim
        echo "updating system packages"
        sudo yum update -y --nogpgcheck
        echo "NOTICE - Updating the ec2-user to keep sudo working"
        sudo chage -d $(( $( date +%s ) / 86400 )) ec2-user
        echo "NOTICE - updating ec2-user sudo config"
        sudo chmod 600 /etc/sudoers && sudo sed -i'' "/ec2-user/d" /etc/sudoers && sudo chmod 400 /etc/sudoers

        
transport:
  name: ssh
  #https://github.com/neillturner/kitchen-ansible/issues/295
  max_ssh_sessions: 2
