Alias ::= 'User_Alias' User_Alias (':' User_Alias)* |
'Runas_Alias' Runas_Alias (':' Runas_Alias)* |
'Host_Alias' Host_Alias (':' Host_Alias)* |
'Cmnd_Alias' Cmnd_Alias (':' Cmnd_Alias)*

User_Alias ::= NAME '=' User_List

Runas_Alias ::= NAME '=' Runas_List

Host_Alias ::= NAME '=' Host_List

Cmnd_Alias ::= NAME '=' Cmnd_List

NAME ::= [A-Z]([A-Z][0-9]_)* 

User_List ::= User |
        User ',' User_List

User ::= '!'* user name |
    '!'* #uid |
    '!'* #x0025group |
    '!'* #x0025#gid |
    '!'* #x002Bnetgroup |
    '!'* #x0025#x003Anonunix_group |
    '!'* #x0025#x003A#nonunix_gid |
    '!'* User_Alias
Runas_List ::= Runas_Member |
Runas_Member ',' Runas_List

Runas_Member ::= '!'* user name |
'!'* #uid |
'!'* #x0025group |
'!'* #x0025#gid |
'!'* #x0025#x003Anonunix_group |
'!'* #x0025#x003A#nonunix_gid |
'!'* #x002Bnetgroup |
'!'* Runas_Alias

Host_List ::= Host |
        Host ',' Host_List

Host ::= '!'* host name |
   '!'* ip_addr |
   '!'* network(/netmask)? |
   '!'* #x002Bnetgroup |
   '!'* Host_Alias

Cmnd_List ::= Cmnd |
        Cmnd ',' Cmnd_List

command name ::= file name |
           file name args |
           file name '""'

Cmnd ::= '!'* command name |
   '!'* directory |
   '!'* "sudoedit" |
   '!'* Cmnd_Alias

Default_Type ::= 'Defaults' |
           'Defaults' '@' Host_List |
           'Defaults' ':' User_List |
           'Defaults' '!' Cmnd_List |
           'Defaults' '>' Runas_List

Default_Entry ::= Default_Type Parameter_List

Parameter_List ::= Parameter |
             Parameter ',' Parameter_List

Parameter ::= Parameter '=' Value |
        Parameter '#x002B=' Value |
        Parameter '-=' Value |
        '!'* Parameter

User_Spec ::= User_List Host_List '=' Cmnd_Spec_List \
        (':' Host_List '=' Cmnd_Spec_List)*

Cmnd_Spec_List ::= Cmnd_Spec |
             Cmnd_Spec ',' Cmnd_Spec_List

Cmnd_Spec ::= Runas_Spec? SELinux_Spec? Tag_Spec* Cmnd

Runas_Spec ::= '(' Runas_List? (':' Runas_List)? ')'

SELinux_Spec ::= ('ROLE=role' | 'TYPE=type')

Tag_Spec ::= ('NOPASSWD:' | 'PASSWD:' | 'NOEXEC:' | 'EXEC:' |
        'SETENV:' | 'NOSETENV:' | 'LOG_INPUT:' | 'NOLOG_INPUT:' |
        'LOG_OUTPUT:' | 'NOLOG_OUTPUT:')