name: Vagrant Testing Matrix

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  my-job:
    name: Validate my profile
    # macos-latest no longer has Vagrant. Must use the specified version per documentation.
    runs-on: macos-12
    env:
      CHEF_LICENSE: accept-silent
      KITCHEN_LOCAL_YAML: kitchen.vagrant.yml
    strategy:
      matrix:
        suite: ['vanilla', 'hardened']
      fail-fast: false
    steps:
      - name: Add jq for output formatting
        run: brew install jq
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Disable ri and rdoc
        run: 'echo "gem: --no-ri --no-rdoc" >> ~/.gemrc'
      - run: bundle install
      - name: Regenerate current `profile.json`
        run: |
          bundle exec inspec json . | jq . > profile.json
      - name: Lint the Inspec profile
        run: bundle exec inspec check .
      - name: Run kitchen test
        run: bundle exec kitchen test --destroy=always ${{ matrix.suite }}-rhel-8 || true
      - name: Save Test Result JSON
        uses: actions/upload-artifact@v2
        with:
          path: spec/results/
      - name: Install SAF CLI
        run: |
          brew install mitre/saf/saf-cli
      - name: Display our ${{ matrix.suite }} results summary
        run: |
          saf view summary -i spec/results/rhel-8_${{ matrix.suite }}.json
      - name: Ensure the scan meets our ${{ matrix.suite }} results threshold
        run: |
          saf validate threshold -i spec/results/rhel-8_${{ matrix.suite }}.json -F ${{ matrix.suite }}.threshold.yml

